/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 raw_assets\Moving_Characters.glb -T -j -M 
Files: raw_assets\Moving_Characters.glb [1.03MB] > C:\Users\andre\My Stuff\VS Code Projects\tutorials\aimees-papercraft-portfolio\Moving_Characters-transformed.glb [121.9KB] (88%)
*/

import { useKTX2Texture } from "../utils/ktxLoader";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useCurveProgressStore } from "../../store/useCurveProgressStore";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/Moving_Characters-transformed.glb",
  );

  const texture_1 = useKTX2Texture("/textures/Moving_Characters_1.webp");

  const curves = useCurveProgressStore((state) => state.curves);
  const scrollProgress = useCurveProgressStore((state) => state.scrollProgress);

  const targetLookAt = useRef(new THREE.Vector3(0, 0, 0));
  const upVector = useRef(new THREE.Vector3(0, 1, 0));

  const winterFrontCharacterRef = useRef();
  const winterSideCharacterRef = useRef();
  const springFrontCharacterRef = useRef();
  const springSideCharacterRef = useRef();
  const summerFrontCharacterRef = useRef();
  const summerWaveRef = useRef();
  const fallFrontCharacterRef = useRef();

  const offsets = {
    winterFrontCharacterRef: 0,
    winterSideCharacterRef: 0.01,
    springFrontCharacterRef: 0.14,
    springSideCharacterRef: 0.14,
    summerFrontCharacterRef: 0.365,
    summerWaveRef: 0.365,
    fallFrontCharacterRef: 0.65,
  };

  const progressMoveRanges = {
    winter: { start: 0, end: 0.12 },
    spring: { start: 0.12, end: 0.33 },
    summer: { start: 0.36, end: 0.6 },
    fall: { start: 0.65, end: 0.85 },
  };

  useEffect(() => {
    if (!curves?.movingCharactersCurve) return;

    const refsAndOffsets = [
      [winterFrontCharacterRef, offsets.winterFrontCharacterRef],
      [winterSideCharacterRef, offsets.winterSideCharacterRef],
      [springFrontCharacterRef, offsets.springFrontCharacterRef],
      [springSideCharacterRef, offsets.springSideCharacterRef],
      [summerFrontCharacterRef, offsets.summerFrontCharacterRef],
      [summerWaveRef, offsets.summerWaveRef],
      [fallFrontCharacterRef, offsets.fallFrontCharacterRef],
    ];

    refsAndOffsets.forEach(([ref, offset]) => {
      if (!ref.current) return;
      curves.movingCharactersCurve.getPointAt(offset, targetPosition.current);
      ref.current.position.copy(targetPosition.current);
    });
  }, [curves]);

  const moveObjectOrCharacter = (ref, offset, range) => {
    if (!ref.current) return;

    const { start, end } = range;

    if (scrollProgress < start || scrollProgress > end) return;

    const rangeProgress = (scrollProgress - start) / (end - start);
    const curveT = offset + rangeProgress * (end - start);

    console.log(scrollProgress);

    const point = curves.movingCharactersCurve.getPointAt(curveT);
    const tangent = curves.movingCharactersCurve.getTangentAt(curveT);

    ref.current.position.copy(point);
    targetLookAt.current.crossVectors(tangent, upVector.current);
    ref.current.lookAt(targetLookAt.current);
  };

  useFrame(() => {
    moveObjectOrCharacter(
      winterFrontCharacterRef,
      offsets.winterFrontCharacterRef,
      progressMoveRanges.winter,
    );
    moveObjectOrCharacter(
      winterSideCharacterRef,
      offsets.winterSideCharacterRef,
      progressMoveRanges.winter,
    );
    moveObjectOrCharacter(
      springFrontCharacterRef,
      offsets.springFrontCharacterRef,
      progressMoveRanges.spring,
    );
    moveObjectOrCharacter(
      springSideCharacterRef,
      offsets.springSideCharacterRef,
      progressMoveRanges.spring,
    );
    moveObjectOrCharacter(
      summerFrontCharacterRef,
      offsets.summerFrontCharacterRef,
      progressMoveRanges.summer,
    );
    moveObjectOrCharacter(
      summerWaveRef,
      offsets.summerWaveRef,
      progressMoveRanges.summer,
    );
    moveObjectOrCharacter(
      fallFrontCharacterRef,
      offsets.fallFrontCharacterRef,
      progressMoveRanges.fall,
    );
  });

  return (
    <group {...props} dispose={null}>
      <group ref={winterFrontCharacterRef}>
        <mesh
          geometry={nodes.Moving_Characters_Winter_arm_left_front.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_arm_left_front.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Winter_arm_right_front.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_arm_right_front.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Winter_front_character.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_front_character.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Winter_Front_Smile.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_Front_Smile.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Winter_front_smile_face.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_front_smile_face.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Winter_happy_face.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_happy_face.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Winter_head_front.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_head_front.position}
        />
      </group>

      <group ref={winterSideCharacterRef}>
        <mesh
          geometry={nodes.Moving_Characters_Winter_left_arm.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_left_arm.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Winter_right_arm.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_right_arm.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Winter_left_foot.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_left_foot.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Winter_right_foot.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_right_foot.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Winter_side.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_side.position}
        />
      </group>

      <group ref={springFrontCharacterRef}>
        <mesh
          geometry={nodes.Moving_Characters_Spring_front.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Spring_front.position}
        />
      </group>
      <group ref={springSideCharacterRef}>
        <mesh
          geometry={nodes.Moving_Characters_Spring_side.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Spring_side.position}
          rotation={nodes.Moving_Characters_Spring_side.rotation}
          scale={nodes.Moving_Characters_Spring_side.scale}
        />
        <mesh
          geometry={nodes.Moving_Characters_Spring_side_back_wheel.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Spring_side_back_wheel.position}
          rotation={nodes.Moving_Characters_Spring_side_back_wheel.rotation}
          scale={nodes.Moving_Characters_Spring_side_back_wheel.scale}
        />
        <mesh
          geometry={nodes.Moving_Characters_Spring_side_front_wheel.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Spring_side_front_wheel.position}
          rotation={nodes.Moving_Characters_Spring_side_front_wheel.rotation}
          scale={nodes.Moving_Characters_Spring_side_front_wheel.scale}
        />
      </group>

      <group ref={fallFrontCharacterRef}>
        <mesh
          geometry={nodes.Moving_Characters_Fall_character.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Fall_character.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Fall_face.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Fall_face.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Fall_left_arm.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Fall_left_arm.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Fall_right_arm.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Fall_right_arm.position}
        />
      </group>

      <group ref={summerWaveRef}>
        <mesh
          geometry={nodes.Moving_Characters_Summer_character_Wave.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Summer_character_Wave.position}
        />
      </group>

      <group ref={summerFrontCharacterRef}>
        <mesh
          geometry={nodes.Moving_Characters_Summer_character.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Summer_character.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Summer_happy_face.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Summer_happy_face.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Summer_left_arm.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Summer_left_arm.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Summer_right_arm.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Summer_right_arm.position}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Moving_Characters-transformed.glb");
