/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 raw_assets\Moving_Characters.glb -T -j -M 
Files: raw_assets\Moving_Characters.glb [1.16MB] > C:\Users\andre\My Stuff\VS Code Projects\tutorials\aimees-papercraft-portfolio\Moving_Characters-transformed.glb [126.24KB] (89%)
*/

import { useKTX2Texture } from "../utils/ktxLoader";
import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/Moving_Characters-transformed.glb",
  );

  const texture_1 = useKTX2Texture("/textures/Moving_Characters_1.webp");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Moving_Characters_Winter_front_character.geometry}
        material={texture_1}
        position={[6.611, -0.723, -8.68]}
        rotation={[0, -0.663, 0]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Winter_right_arm.geometry}
        material={texture_1}
        position={[7.579, 1.342, -7.52]}
        rotation={[1.574, -0.003, 0.787]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Winter_left_arm.geometry}
        material={texture_1}
        position={[7.609, 1.342, -7.55]}
        rotation={[1.574, -0.003, 0.787]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Fall_character.geometry}
        material={texture_1}
        position={[-11.117, 1.97, -1.026]}
        rotation={[Math.PI / 2, 0, -1.478]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Summer_left_arm.geometry}
        material={texture_1}
        position={[-2.338, 1.378, 11.477]}
        rotation={[1.624, -0.793, -3.067]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Summer_right_arm.geometry}
        material={texture_1}
        position={[-1.617, 1.415, 11.507]}
        rotation={[-1.637, -0.9, 3.057]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Summer_happy_face.geometry}
        material={texture_1}
        position={[-1.765, 2.004, 11.497]}
        rotation={[1.605, 0.858, -3.127]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Winter_side.geometry}
        material={texture_1}
        position={[7.597, 1.04, -7.511]}
        rotation={[Math.PI / 2, 0, 0.787]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Winter_right_foot.geometry}
        material={texture_1}
        position={[7.598, 0.789, -7.514]}
        rotation={[-1.601, -0.03, -0.787]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Winter_left_foot.geometry}
        material={texture_1}
        position={[7.623, 0.787, -7.519]}
        rotation={[-1.601, -0.03, -0.787]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Spring_side.geometry}
        material={texture_1}
        position={[11.358, 0.985, 2.023]}
        rotation={[-1.612, 0.01, -1.797]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Summer_character.geometry}
        material={texture_1}
        position={[-1.018, 0.444, 11.927]}
        rotation={[Math.PI, -1.337, Math.PI]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Spring_front.geometry}
        material={texture_1}
        position={[11.76, -0.78, 0.718]}
        rotation={[0, -0.625, 0]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Winter_arm_left_front.geometry}
        material={texture_1}
        position={[6.645, 1.243, -8.438]}
        rotation={[1.069, 0.525, 0.83]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Winter_arm_right_front.geometry}
        material={texture_1}
        position={[6.353, 1.232, -8.679]}
        rotation={[1.069, 0.525, 0.83]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Winter_front_smile.geometry}
        material={texture_1}
        position={[6.501, 1.446, -8.561]}
        rotation={[Math.PI / 2, 0, 0.685]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Winter_front_smile_face.geometry}
        material={texture_1}
        position={[6.498, 1.444, -8.553]}
        rotation={[Math.PI / 2, 0, 0.69]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Winter_happy_face.geometry}
        material={texture_1}
        position={[6.498, 1.728, -8.561]}
        rotation={[1.059, 0.646, -2.327]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Winter_head_front.geometry}
        material={texture_1}
        position={[6.507, 1.699, -8.566]}
        rotation={[Math.PI / 2, 0, 0.692]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Fall_face.geometry}
        material={texture_1}
        position={[-11.111, 1.697, -1.016]}
        rotation={[Math.PI / 2, 0, -1.478]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Fall_left_arm.geometry}
        material={texture_1}
        position={[-11.094, 1.545, -1.177]}
        rotation={[2.278, 0.061, -1.5]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Fall_right_arm.geometry}
        material={texture_1}
        position={[-11.132, 1.537, -0.876]}
        rotation={[2.278, 0.061, -1.5]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Spring_side_back_wheel.geometry}
        material={texture_1}
        position={[11.438, 0.708, 1.683]}
        rotation={[-1.563, -0.06, -1.606]}
      />
      <mesh
        geometry={nodes.Moving_Characters_Spring_side_front_wheel.geometry}
        material={texture_1}
        position={[11.237, 0.734, 2.54]}
        rotation={[-0.605, -0.191, -1.701]}
      />
    </group>
  );
}

useGLTF.preload("/models/Moving_Characters-transformed.glb");
