/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 raw_assets\Scene_2_Spring.glb -T -j -M 
Files: raw_assets\Scene_2_Spring.glb [1.71MB] > C:\Users\andre\My Stuff\VS Code Projects\tutorials\aimees-papercraft-portfolio\Scene_2_Spring-transformed.glb [413.8KB] (76%)
*/

import { useKTX2Texture } from "../utils/ktxLoader";
import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/Scene_2_Spring-transformed.glb",
  );

  const texture_1 = useKTX2Texture("/textures/Scene_2_Spring_1.webp");
  const texture_2 = useKTX2Texture("/textures/Scene_2_Spring_2.webp");
  const texture_3 = useKTX2Texture("/textures/Scene_2_Spring_3.webp");
  const texture_4 = useKTX2Texture("/textures/Scene_2_Spring_4.webp");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Scene_2_Spring_1_Baked.geometry}
        material={texture_1}
        position={[-0.025, 0.731, 0.683]}
        rotation={[0, -0.655, 0]}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_2_Gate_Right.geometry}
        material={texture_2}
        position={[6.732, 1.103, 9.175]}
        rotation={[0, -0.994, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_2_Gate_Left.geometry}
        material={texture_2}
        position={[7.862, 1.103, 10.914]}
        rotation={[0, -0.994, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_2_Fox_Head.geometry}
        material={texture_2}
        position={[10.082, 0.533, 8.884]}
        rotation={[-0.795, -0.369, -1.924]}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Baked.geometry}
        material={texture_3}
        position={[4.871, -1.152, 1.692]}
        rotation={[0, 0.069, 0]}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Fish.geometry}
        material={texture_3}
        position={[4.871, -1.152, 1.692]}
        rotation={[0, 0.069, 0]}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Water_Outer.geometry}
        material={texture_3}
        position={[4.871, -1.152, 1.692]}
        rotation={[0, 0.069, 0]}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Water_Inner.geometry}
        material={texture_3}
        position={[4.871, -1.152, 1.692]}
        rotation={[0, 0.069, 0]}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_4_Baked.geometry}
        material={texture_4}
        position={[-0.025, -1.161, 0.683]}
        rotation={[0, -0.655, 0]}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_2_Baked.geometry}
        material={texture_2}
        position={[11.441, 3.708, 6.817]}
        rotation={[-0.795, -0.369, -1.924]}
      />
    </group>
  );
}

useGLTF.preload("/models/Scene_2_Spring-transformed.glb");
