/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 raw_assets\Scene_3_Summer.glb -T -j -M 
Files: raw_assets\Scene_3_Summer.glb [4.09MB] > C:\Users\andre\My Stuff\VS Code Projects\tutorials\aimees-papercraft-portfolio\Scene_3_Summer-transformed.glb [417.36KB] (90%)
*/

import { useKTX2Texture } from "../utils/ktxLoader";
import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/Scene_3_Summer-transformed.glb",
  );

  const texture_1 = useKTX2Texture("/textures/Scene_3_Summer_1.webp");
  const texture_2 = useKTX2Texture("/textures/Scene_3_Summer_2.webp");
  const texture_3 = useKTX2Texture("/textures/Scene_3_Summer_3.webp");
  const texture_4 = useKTX2Texture("/textures/Scene_3_Summer_4.webp");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Scene_3_Summer_1.geometry}
        material={texture_1}
        position={[-12.913, 5.063, 3.973]}
        rotation={[-1.886, -0.063, -1.359]}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2.geometry}
        material={texture_2}
        position={[-0.025, 1.688, 0.683]}
        rotation={[0, -0.655, 0]}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2_Figma_Sign_Summer_3_2.geometry}
        material={texture_2}
        position={[-8.308, -0.316, 7.066]}
        rotation={[0, -0.864, 0]}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2_Psychiatrist_Sign_Summer_3_2.geometry}
        material={texture_2}
        position={[-8.972, -1.152, 3.654]}
        rotation={[0, -0.724, 0]}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2_Blender_Sign_Summer_3_2.geometry}
        material={texture_2}
        position={[-4.71, -0.647, 9.861]}
        rotation={[0, -0.784, 0]}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_3.geometry}
        material={texture_3}
        position={[-2.036, 8.657, 6.085]}
        scale={0.191}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_4_Starbucks_Sign_Summer_3_2.geometry}
        material={texture_4}
        position={[-2.001, -1.191, 9.985]}
        rotation={[0, -0.256, 0]}
        scale={[1, 1.75, 1]}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2.geometry}
        material={texture_4}
        position={[-2.359, -6.377, 8.422]}
        rotation={[0, -0.439, 0]}
        scale={[1, 1.75, 1]}
      />
    </group>
  );
}

useGLTF.preload("/models/Scene_3_Summer-transformed.glb");
