/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 raw_assets\Scene_4_Fall.glb -T -j -M 
Files: raw_assets\Scene_4_Fall.glb [2.05MB] > C:\Users\andre\My Stuff\VS Code Projects\tutorials\aimees-papercraft-portfolio\Scene_4_Fall-transformed.glb [133.52KB] (93%)
*/

import { useKTX2Texture } from "../utils/ktxLoader";
import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/Scene_4_Fall-transformed.glb");

  const texture_1 = useKTX2Texture("/textures/Scene_4_Fall_1.webp");
  const texture_2 = useKTX2Texture("/textures/Scene_4_Fall_2.webp");
  const texture_3 = useKTX2Texture("/textures/Scene_4_Fall_3.webp");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Scene_4_Fall_1_Baked.geometry}
        material={texture_1}
        position={[-0.025, 0.731, 0.683]}
        rotation={[0, -0.655, 0]}
      />
      <mesh
        geometry={nodes.Scene_4_Fall_2_Baked.geometry}
        material={texture_2}
        position={[-0.025, 0.731, 0.683]}
        rotation={[0, -0.655, 0]}
      />
      <mesh
        geometry={nodes.Scene_4_Fall_2_Left_Arm.geometry}
        material={texture_2}
        position={[-4.24, -0.335, -8.168]}
        rotation={[-0.206, -0.697, -0.14]}
      />
      <mesh
        geometry={nodes.Scene_4_Fall_2_Right_Arm.geometry}
        material={texture_2}
        position={[-4.75, -0.325, -7.783]}
        rotation={[0.086, -0.637, 0.057]}
      />
      <mesh
        geometry={nodes.Scene_4_Fall_2_Fire.geometry}
        material={texture_2}
        position={[-4.773, -0.05, -7.765]}
        rotation={[0, -0.655, 0]}
      />
      <mesh
        geometry={nodes.Scene_4_Fall_3_Baked.geometry}
        material={texture_3}
        position={[-0.025, 0.739, 0.683]}
        rotation={[0, -0.655, 0]}
      />
      <mesh
        geometry={nodes.Scene_4_Fall_3_Cat_Head.geometry}
        material={texture_3}
        position={[-4.15, 0.711, -11.922]}
        rotation={[0, -0.655, 0]}
      />
      <mesh
        geometry={nodes.Scene_4_Fall_3_Baked001.geometry}
        material={texture_3}
        position={[-7.457, 0.811, -10.109]}
        rotation={[0, -0.655, 0]}
      />
      <mesh
        geometry={nodes.Scene_4_Fall_3_Baked002.geometry}
        material={texture_3}
        position={[-10.349, 0.626, -7.59]}
        rotation={[-0.412, -0.645, -0.251]}
      />
    </group>
  );
}

useGLTF.preload("/models/Scene_4_Fall-transformed.glb");
