/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 raw_assets\Scene_1_Winter.glb -T -j -M 
Files: raw_assets\Scene_1_Winter.glb [2.79MB] > C:\Users\andre\My Stuff\VS Code Projects\tutorials\aimees-papercraft-portfolio\Scene_1_Winter-transformed.glb [225.48KB] (92%)
*/

import { useKTX2Texture } from "../utils/ktxLoader";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { AnimateMesh } from "../components/AnimateMesh";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/Scene_1_Winter-transformed.glb",
  );

  const texture_1 = useKTX2Texture("/textures/Scene_1_Winter_1.webp", false);
  const texture_2 = useKTX2Texture("/textures/Scene_1_Winter_2.webp", false);
  const texture_3 = useKTX2Texture("/textures/Scene_1_Winter_3.webp", false);
  const texture_4 = useKTX2Texture("/textures/Scene_1_Winter_4.webp", false);

  const deerHeadRef = useRef();

  useFrame((state) => {
    if (!deerHeadRef) return;
    const time = state.clock.elapsedTime;

    // deerHeadRef.current.rotation.z = 0.2 * Math.sin(time);
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Scene_1_Winter_1_Baked.geometry}
        material={texture_1}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_2_Baked.geometry}
        material={texture_2}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Player.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Bird_Wing.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Bird_Tail.geometry}
        material={texture_3}
      />

      <AnimateMesh
        position={nodes.Scene_1_Winter_3_Deer_Head.position}
        axis={"z"}
        amplitude={0.2}
        speed={1.5}
      >
        <mesh
          geometry={nodes.Scene_1_Winter_3_Deer_Head.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <mesh
        geometry={nodes.Scene_1_Winter_3_Fire_Inner_Most.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Fire_Center.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Fire_Outer.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Bird_Baked.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Chat_Box_Scene_1_Winter_3.geometry}
        material={texture_3}
      />
      <AnimateMesh axis={"z"} amplitude={0.01}>
        <mesh
          geometry={nodes.Scene_1_Winter_3_Note_1.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <AnimateMesh axis={"z"} amplitude={0.012} speed={0.95}>
        <mesh
          geometry={nodes.Scene_1_Winter_3_Note_2.geometry}
          material={texture_3}
        />
      </AnimateMesh>
      <AnimateMesh axis={"z"} offset={0.3} amplitude={0.011} speed={0.99}>
        <mesh
          geometry={nodes.Scene_1_Winter_3_Note_3.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <mesh
        geometry={nodes.Scene_1_Winter_3_Hello_Text.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Thanks_Baked.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Welcome_Baked.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Flame_3.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Flame_1.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_3_Flame_2.geometry}
        material={texture_3}
      />
      <mesh
        geometry={nodes.Scene_1_Winter_4_Baked.geometry}
        material={texture_4}
      />
    </group>
  );
}

useGLTF.preload("/models/Scene_1_Winter-transformed.glb");
