/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 raw_assets\Scene_3_Summer.glb -T -j -M 
Files: raw_assets\Scene_3_Summer.glb [4.09MB] > C:\Users\andre\My Stuff\VS Code Projects\tutorials\aimees-papercraft-portfolio\Scene_3_Summer-transformed.glb [417.36KB] (90%)
*/

import { useKTX2Texture } from "../utils/ktxLoader";
import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/Scene_3_Summer-transformed.glb",
  );

  const texture_1 = useKTX2Texture("/textures/Scene_3_Summer_1.webp");
  const texture_2 = useKTX2Texture("/textures/Scene_3_Summer_2.webp");
  const texture_3 = useKTX2Texture("/textures/Scene_3_Summer_3.webp");
  const texture_4 = useKTX2Texture("/textures/Scene_3_Summer_4.webp");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Scene_3_Summer_1.geometry}
        material={texture_1}
        position={nodes.Scene_3_Summer_1.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_Shanghai.geometry}
        material={texture_1}
        position={nodes.Scene_3_Summer_Shanghai.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_Austin.geometry}
        material={texture_1}
        position={nodes.Scene_3_Summer_Austin.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_1_Cali.geometry}
        material={texture_1}
        position={nodes.Scene_3_Summer_1_Cali.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_1_Boston.geometry}
        material={texture_1}
        position={nodes.Scene_3_Summer_1_Boston.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2_Figma_Sign_Summer_3_2.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2_Figma_Sign_Summer_3_2.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2_Psychiatrist_Sign_Summer_3_2.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2_Psychiatrist_Sign_Summer_3_2.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2_Blender_Sign_Summer_3_2.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2_Blender_Sign_Summer_3_2.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2_seaweed.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2_seaweed.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2001_seaweed.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2001_seaweed.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2002_seaweed.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2002_seaweed.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2003_seaweed.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2003_seaweed.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2001_fish.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2001_fish.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2001_fish_two.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2001_fish_two.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2001_starfish.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2001_starfish.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2001_seahorse.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2001_seahorse.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_3.geometry}
        material={texture_3}
        position={nodes.Scene_3_Summer_3.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_4_Starbucks_Sign_Summer_3_2.geometry}
        material={texture_4}
        position={nodes.Scene_3_Summer_4_Starbucks_Sign_Summer_3_2.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2_Crab.geometry}
        material={texture_4}
        position={nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2_Crab.position}
      />
      <mesh
        geometry={
          nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2_Dragonair.geometry
        }
        material={texture_4}
        position={
          nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2_Dragonair.position
        }
      />
      <mesh
        geometry={
          nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2_Sand_Castle_Gate.geometry
        }
        material={texture_4}
        position={
          nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2_Sand_Castle_Gate.position
        }
      />
      <mesh
        geometry={
          nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2001_umbrella.geometry
        }
        material={texture_4}
        position={
          nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2001_umbrella.position
        }
      />
      <mesh
        geometry={nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2.geometry}
        material={texture_4}
        position={nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2.position}
      />
    </group>
  );
}

useGLTF.preload("/models/Scene_3_Summer-transformed.glb");
