/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 raw_assets\Spring.glb -T -j -M 
Files: raw_assets\Spring.glb [1.47MB] > C:\Users\andre\My Stuff\VS Code Projects\tutorials\aimees-papercraft-portfolio\Scene_2_Spring-transformed.glb [392.27KB] (73%)
*/

import { useKTX2Texture } from "../utils/ktxLoader";
import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/Scene_2_Spring-transformed.glb",
  );

  const texture_1 = useKTX2Texture("/textures/Scene_2_Spring_1.webp");
  const texture_2 = useKTX2Texture("/textures/Scene_2_Spring_2.webp");
  const texture_3 = useKTX2Texture("/textures/Scene_2_Spring_3.webp");
  const texture_4 = useKTX2Texture("/textures/Scene_2_Spring_4.webp");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Scene_2_Spring_1_Baked.geometry}
        material={texture_1}
        position={nodes.Scene_2_Spring_1_Baked.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_2_Gate_Right.geometry}
        material={texture_2}
        position={nodes.Scene_2_Spring_2_Gate_Right.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_2_Gate_Left.geometry}
        material={texture_2}
        position={nodes.Scene_2_Spring_2_Gate_Left.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_2_Fox_Head.geometry}
        material={texture_2}
        position={nodes.Scene_2_Spring_2_Fox_Head.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_2_Baked_Slime.geometry}
        material={texture_2}
        position={nodes.Scene_2_Spring_2_Baked_Slime.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_2_Baked_Gnome.geometry}
        material={texture_2}
        position={nodes.Scene_2_Spring_2_Baked_Gnome.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_2_Baked_Gnome002.geometry}
        material={texture_2}
        position={nodes.Scene_2_Spring_2_Baked_Gnome002.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_2_Baked_Gnome001.geometry}
        material={texture_2}
        position={nodes.Scene_2_Spring_2_Baked_Gnome001.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_2_Baked_Butterfly.geometry}
        material={texture_2}
        position={nodes.Scene_2_Spring_2_Baked_Butterfly.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Fish.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Fish.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Water_Outer.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Water_Outer.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Water_Inner.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Water_Inner.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Baked_Duck.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Baked_Duck.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Baked_Frog.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Baked_Frog.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Baked_Grass.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Baked_Grass.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Baked_Grass001.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Baked_Grass001.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Baked_Grass002.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Baked_Grass002.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Baked_Grass003.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Baked_Grass003.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Baked_Flower.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Baked_Flower.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Baked001.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Baked001.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Baked_Flower001.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Baked_Flower001.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Baked002.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Baked002.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Baked_Plant.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Baked_Plant.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Baked_Plant001.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Baked_Plant001.position}
      />

      <mesh
        geometry={nodes.Scene_2_Spring_3_Baked003.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Baked003.position}
        rotation={nodes.Scene_2_Spring_3_Baked003.rotation}
      />

      <mesh
        geometry={nodes.Scene_2_Spring_4_Baked.geometry}
        material={texture_4}
        position={nodes.Scene_2_Spring_4_Baked.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_2_Baked.geometry}
        material={texture_2}
        position={nodes.Scene_2_Spring_2_Baked.position}
      />
    </group>
  );
}

useGLTF.preload("/models/Scene_2_Spring-transformed.glb");
