/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 raw_assets\wintaaa.glb -T -j -M 
Files: raw_assets\wintaaa.glb [250.75KB] > C:\Users\andre\My Stuff\VS Code Projects\tutorials\aimees-papercraft-portfolio\wintaaa-transformed.glb [244.44KB] (3%)
*/

import { useTexture } from "../utils/ktxLoader";
import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/wintaaa-transformed.glb')

  const texture_1 = useTexture("/textures/wintaaa_1.webp");
  const texture_2 = useTexture("/textures/wintaaa_2.webp");
  const texture_3 = useTexture("/textures/wintaaa_3.webp");
  const texture_4 = useTexture("/textures/wintaaa_4.webp");

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Scene_1_Winter_1_Baked.geometry} material={texture_1} position={nodes.Scene_1_Winter_1_Baked.position} />
      <mesh geometry={nodes.Scene_1_Winter_2_Baked.geometry} material={texture_1} position={nodes.Scene_1_Winter_2_Baked.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Player.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Player.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Bird_Wing.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Bird_Wing.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Bird_Tail.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Bird_Tail.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Deer_Head.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Deer_Head.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Fire_Inner_Most.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Fire_Inner_Most.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Fire_Center.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Fire_Center.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Fire_Outer.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Fire_Outer.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Bird_Baked.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Bird_Baked.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Chat_Box_Scene_1_Winter_3.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Chat_Box_Scene_1_Winter_3.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Note_1.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Note_1.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Note_2.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Note_2.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Note_3.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Note_3.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Hello_Text.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Hello_Text.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Thanks_Baked.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Thanks_Baked.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Welcome_Baked.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Welcome_Baked.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Flame_3.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Flame_3.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Flame_1.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Flame_1.position} />
      <mesh geometry={nodes.Scene_1_Winter_3_Flame_2.geometry} material={texture_1} position={nodes.Scene_1_Winter_3_Flame_2.position} />
      <mesh geometry={nodes.Scene_1_Winter_4_Baked.geometry} material={texture_1} position={nodes.Scene_1_Winter_4_Baked.position} />
    </group>
  )
}

useGLTF.preload('/models/wintaaa-transformed.glb')
